CREATE OR REPLACE PROCEDURE PR_INSERIR_ESP32 AS
BEGIN
    INSERT INTO T_ST_ESP32 DEFAULT VALUES;

    DBMS_OUTPUT.PUT_LINE('ESP32 criado com sucesso.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro ao criar ESP32: ' || SQLERRM);
END;
/
